    &lt;ul class="fat-scroll-list"&gt;
        &lt;li&gt;One&lt;/li&gt;
        &lt;li&gt;Two&lt;/li&gt;
        &lt;li&gt;Three&lt;/li&gt;
        &lt;li&gt;Four&lt;/li&gt;
        &lt;li&gt;Five&lt;/li&gt;
        &lt;li&gt;Six&lt;/li&gt;
        &lt;li&gt;Seven&lt;/li&gt;
        &lt;li&gt;Eight&lt;/li&gt;
        &lt;li&gt;Nine&lt;/li&gt;
        &lt;li&gt;Ten&lt;/li&gt;
        &lt;li&gt;Eleven&lt;/li&gt;
        &lt;li&gt;Twelve&lt;/li&gt;
        &lt;li&gt;Thirteen&lt;/li&gt;
        &lt;li&gt;Fourteen&lt;/li&gt;
        &lt;li&gt;Fifteen&lt;/li&gt;
        &lt;li&gt;Sixteen&lt;/li&gt;
        &lt;li&gt;Seventeen&lt;/li&gt;
        &lt;li&gt;Eighteen&lt;/li&gt;
        &lt;li&gt;Nineteen&lt;/li&gt;
        &lt;li&gt;Twenty&lt;/li&gt;
        &lt;li&gt;Twenty One&lt;/li&gt;
        &lt;li&gt;Twenty Two&lt;/li&gt;
        &lt;li&gt;Twenty Three&lt;/li&gt;
        &lt;li&gt;Twenty Four&lt;/li&gt;
        &lt;li&gt;Twenty Five&lt;/li&gt;
        &lt;li&gt;Twenty Six&lt;/li&gt;
        &lt;li&gt;Twenty Seven&lt;/li&gt;
        &lt;li&gt;Twenty Eight&lt;/li&gt;
        &lt;li&gt;Twenty Nine&lt;/li&gt;
        &lt;li&gt;Thirty&lt;/li&gt;
        &lt;li&gt;Thirty One&lt;/li&gt;
        &lt;li&gt;Thirty Two&lt;/li&gt;
        &lt;li&gt;Thirty Three&lt;/li&gt;
        &lt;li&gt;Thirty Four&lt;/li&gt;
        &lt;li&gt;Thirty Five&lt;/li&gt;
        &lt;li&gt;Thirty Six&lt;/li&gt;
        &lt;li&gt;Thirty Seven&lt;/li&gt;
        &lt;li&gt;Thirty Eight&lt;/li&gt;
        &lt;li&gt;Thirty Nine&lt;/li&gt;
        &lt;li&gt;Forty&lt;/li&gt;
        &lt;li&gt;Forty One&lt;/li&gt;
        &lt;li&gt;Forty Two&lt;/li&gt;
        &lt;li&gt;Forty Three&lt;/li&gt;
        &lt;li&gt;Forty Four&lt;/li&gt;
        &lt;li&gt;Forty Five&lt;/li&gt;
        &lt;li&gt;Forty Six&lt;/li&gt;
        &lt;li&gt;Forty Seven&lt;/li&gt;
        &lt;li&gt;Forty Eight&lt;/li&gt;
        &lt;li&gt;Forty Nine&lt;/li&gt;
        &lt;li&gt;Fifty&lt;/li&gt;
    &lt;/ul&gt;